title: <p align="center"> Ravi Teja Tamvada </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/RT_Tamvada_resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rtamvada/">LinkedIn</a> |
  <a href="https://github.com/rtamvada">GitHub</a>
  
  <br>   
  I am pursuing an Executive PG Program in ML/AI from IIIT-Bangalore.
  I have hands-on knowledge on coding in Python, NumPy, Pandas, Matplotlib, Seaborn libraries.
  Also, I have 7yrs of experience as an Embedded Software Developer and currently working with Nvidia.
  <br>
  </p>



theme: jekyll-theme-minimal
